name: Build

on:
  push:
    branches:
      - canary
      - develop
      - main
  pull_request:
    branches:
      - main
      - canary
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_PAT}}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Build all monorepo
        run: yarn build
