name: Canary Release

on:
  push:
    branches:
      - canary

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Canary Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_PAT}}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Canary Version
        run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Canary Version
        run: |
          yarn changeset version --snapshot canary
          echo "PACKAGE_VERSION=$(node -p "require('./packages/lib/package.json').version")" >> $GITHUB_ENV

      - name: Publish canary version
        run: yarn changeset publish --tag canary

      - name: Create Release Tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: true
