name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_PAT}}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      # Create release PR
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # EDIT PR
      - name: (EDIT PR) Get PR number
        if: steps.changesets.outputs.hasChangesets == 'true'
        id: pr_number
        run: echo "::set-output name=number::$(gh pr view https://github.com/${{ github.repository }}/pull/${{ steps.changesets.outputs.pullRequestId }} --json number -q .number)"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: (EDIT PR) Get new version of package
        if: steps.changesets.outputs.hasChangesets == 'true'
        id: new_version
        run: echo "::set-output name=version::$(node -p "require('./packages/lib/package.json').version")"

      - name: (EDIT PR) Update PR title
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: gh pr edit ${{ steps.pr_number.outputs.number }} --title "Release ${{ steps.new_version.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      # Publish Package if no changesets
      - name: Creating .npmrc
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          yarn build && yarn changeset publish
          echo "PACKAGE_VERSION=$(node -p "require('./packages/lib/package.json').version")" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Tag
        if: steps.changesets.outputs.hasChangesets == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
